CREATE TABLE CARGO (
CODIGO INTEGER NOT NULL ,
NOME VARCHAR (30) NOT NULL ,
SALARIO FLOAT NOT NULL ,
PRIMARY KEY (CODIGO)
);

ALTER TABLE CARGO RENAME TO POSITION ;

ALTER TABLE POSITION RENAME COLUMN CODIGO TO CODE ;
ALTER TABLE POSITION RENAME COLUMN NOME TO NAME ;
ALTER TABLE POSITION RENAME COLUMN SALARIO TO WAGE ;

CREATE TABLE DEPARTMENT (
CODE SERIAL NOT NULL ,
NAME VARCHAR (30) NOT NULL ,
PRIMARY KEY (CODE)
);

CREATE SEQUENCE SEQ_FUNCIONARIO START WITH 1 ;

CREATE TABLE FUNCIONARIO (
REGISTRO INTEGER NOT NULL ,
NOME VARCHAR (30) NOT NULL ,
SEXO VARCHAR (1) NOT NULL ,
PRIMARY KEY (REGISTRO)
);

ALTER TABLE FUNCIONARIO ADD COLUMN NASCIMENTO TIMESTAMP NULL ;

